// Atrium Senda — Dataset Padrão de Configurações do Escritório (ADVBOX)
(function (root, factory) {
  const data = factory();
  if (typeof module === 'object' && module.exports) {
    module.exports = data;
  }
  if (typeof root === 'object' && root) {
    root.OFFICE_DEFAULT_DATA = data;
  }
}(typeof self !== 'undefined' ? self : (typeof globalThis !== 'undefined' ? globalThis : this), function () {
  'use strict';

  const actionGroups = [
    { name: 'Cível', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Previdenciário', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Trabalhista', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Tributário', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Família', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Consumidor', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Criminal', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Administrativo', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Serviços', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Precatório', publicationResponsible: 'Ricardo De Luca Rossetto' },
    { name: 'Financeiro/rh', publicationResponsible: 'Ricardo De Luca Rossetto' }
  ];

  const taskDefinitions = [
    { name: '1º CONTATO COM O LEAD', points: 10, phase: 'Negociação' },
    { name: 'ABERTURA DE DIT PERANTE A FAZENDA ESTADUAL', points: 70, phase: 'Judicial' },
    { name: 'ACOMPANHAR CITAÇÃO', points: 20, phase: 'Judicial' },
    { name: 'ACOMPANHAR DECISÃO/ACÓRDÃO', points: 20, phase: 'Recursal' },
    { name: 'ACOMPANHAR DECISÃO/DESPACHO', points: 10, phase: 'Judicial' },
    { name: 'ACOMPANHAR PAGAMENTO', points: 10, phase: 'Execução/cobrança' },
    { name: 'ACOMPANHAR PERÍCIA', points: 20, phase: 'Judicial' },
    { name: 'ACOMPANHAR TRÂNSITO EM JULGADO', points: 10, phase: 'Judicial' },
    { name: 'AGRAVO DE INSTRUMENTO', points: 90, phase: 'Judicial' },
    { name: 'AGRAVO EM RECURSO ESPECIAL E EXTRAORDINÁRIO', points: 400, phase: 'Recursal' },
    { name: 'AGRAVO INTERNO', points: 100, phase: 'Recursal' },
    { name: 'AGUARDANDO DOCUMENTOS CLIENTE', points: 5, phase: 'Administrativo' },
    { name: 'AGUARDANDO DOCUMENTOS PARCEIRO', points: 5, phase: 'Administrativo' },
    { name: 'ALEGAÇÕES FINAIS COMPLEXAS', points: 120, phase: 'Judicial' },
    { name: 'ALEGAÇÕES FINAIS SIMPLES', points: 80, phase: 'Judicial' },
    { name: 'ANÁLISE DE CASO DO PARCEIRO', points: 50, phase: 'Marketing' },
    { name: 'ANÁLISE DE PROPOSTA DE ACORDO', points: 80, phase: 'Administrativo' },
    { name: 'ANÁLISE DE PROPOSTA DE ACORDO COMPLEXA', points: 120, phase: 'Administrativo' },
    { name: 'ANÁLISE DO CASO', points: 50, phase: 'Negociação' },
    { name: 'ATRIBUIR E-MAIL/NOTA DE EXPEDIENTE E TAREFA', points: 5, phase: 'Judicial' },
    { name: 'AUDIÊNCIA DE CONCILIAÇÃO', points: 100, phase: 'Judicial' },
    { name: 'AUDIÊNCIA DE INSTRUÇÃO/JULGAMENTO', points: 150, phase: 'Judicial' },
    { name: 'AUDIÊNCIA PRELIMINAR', points: 90, phase: 'Judicial' },
    { name: 'AVALIAR DOCUMENTAÇÃO PROBATÓRIA', points: 50, phase: 'Negociação' },
    { name: 'AVISAR CLIENTE DA AUDIÊNCIA', points: 10, phase: 'Judicial' },
    { name: 'AVISAR CLIENTE DA DATA DA SUSTENTAÇÃO ORAL', points: 10, phase: 'Recursal' },
    { name: 'AVISAR CLIENTE DA PERÍCIA', points: 5, phase: 'Judicial' },
    { name: 'BUSCAR INFORMAÇÕES EM ÓRGÃO PÚBLICO', points: 30, phase: 'Administrativo' },
    { name: 'CARGA DE PROCESSO', points: 5, phase: 'Judicial' },
    { name: 'COBRAR HONORÁRIOS/ENVIAR BOLETO', points: 30, phase: 'Todas' },
    { name: 'COLETA DE PROVAS', points: 120, phase: 'Administrativo' },
    { name: 'COMPRAR MATERIAL PARA O ESCRITÓRIO', points: 40, phase: 'Rh/financeiro' },
    { name: 'CONFERIR CÁLCULO DO PERITO/DA PARTE', points: 30, phase: 'Execução/cobrança' },
    { name: 'CONFERIR/REVISAR PETIÇÃO', points: 30, phase: 'Judicial' },
    { name: 'CONTESTAÇÃO COM MODELO', points: 50, phase: 'Judicial' },
    { name: 'CONTESTAÇÃO COMPLEXA', points: 150, phase: 'Judicial' },
    { name: 'CONTESTAÇÃO SEM MODELO', points: 100, phase: 'Judicial' },
    { name: 'CONTRATAR CORRESPONDENTE/PARCEIRO', points: 40, phase: 'Administrativo' },
    { name: 'CUMPRIMENTO DE EXIGÊNCIAS', points: 30, phase: 'Administrativo' },
    { name: 'DAR PALESTRA EM EVENTO', points: 25, phase: 'Marketing' },
    { name: 'DESPACHO COM JUIZ', points: 100, phase: 'Judicial' },
    { name: 'DESPACHO COM DESEMBARGADOR', points: 80, phase: 'Recursal' },
    { name: 'DESPACHO COM MINISTRO', points: 80, phase: 'Recursal' },
    { name: 'DESPACHO/PROTOCOLO NO CARTÓRIO', points: 30, phase: 'Judicial' },
    { name: 'DEVOLUÇÃO DE DOCUMENTOS/PROCESSO', points: 5, phase: 'Todas' },
    { name: 'DIGITALIZAÇÃO DE DOCUMENTOS', points: 10, phase: 'Todas' },
    { name: 'DILIGÊNCIA EM CARTÓRIO', points: 10, phase: 'Execução/cobrança' },
    { name: 'EDIÇÃO DE ARTE PARA REDE SOCIAL', points: 20, phase: 'Marketing' },
    { name: 'EFETUAR PAGAMENTO', points: 10, phase: 'Administrativo' },
    { name: 'ELABORAR CÁLCULO SIMPLES', points: 30, phase: 'Judicial' },
    { name: 'ELABORAR CONTRARRAZÕES', points: 110, phase: 'Recursal' },
    { name: 'ELABORAR DECLARAÇÕES FINAIS', points: 30, phase: 'Judicial' },
    { name: 'ELABORAR DECLARAÇÕES INICIAIS', points: 50, phase: 'Judicial' },
    { name: 'ELABORAR ESBOÇO DE PARTILHA', points: 70, phase: 'Judicial' },
    { name: 'ELABORAR NOTIFICAÇÃO EXTRAJUDICIAL', points: 70, phase: 'Administrativo' },
    { name: 'ELABORAR PETIÇÃO COMPLEXA', points: 150, phase: 'Judicial' },
    { name: 'ELABORAR PETIÇÃO DE ACORDO', points: 30, phase: 'Administrativo' },
    { name: 'ELABORAR PETIÇÃO DE CUMPRIMENTO DE SENTENÇA', points: 100, phase: 'Execução/cobrança' },
    { name: 'ELABORAR PETIÇÃO DE EXECUÇÃO', points: 100, phase: 'Execução/cobrança' },
    { name: 'ELABORAR PETIÇÃO DE LIQUIDAÇÃO (TRABALHISTA)', points: 10, phase: 'Execução/cobrança' },
    { name: 'ELABORAR PETIÇÃO INICIAL COM MODELO', points: 50, phase: 'Judicial' },
    { name: 'ELABORAR PETIÇÃO INICIAL SEM MODELO', points: 100, phase: 'Judicial' },
    { name: 'ELABORAR PLANO DE CARTILHA', points: 30, phase: 'Judicial' },
    { name: 'ELABORAR PROPOSTA DE ACORDO', points: 50, phase: 'Administrativo' },
    { name: 'ELABORAR QUESITOS', points: 50, phase: 'Judicial' },
    { name: 'ELABORAR RECURSO ADMINISTRATIVO', points: 120, phase: 'Administrativo' },
    { name: 'ELABORAR RELATÓRIO PROCESSUAL', points: 30, phase: 'Judicial' },
    { name: 'ELABORAR REQUERIMENTO ADMINISTRATIVO', points: 150, phase: 'Administrativo' },
    { name: 'ELABORAR RESUMO DA DECISÃO PARA O INSS', points: 20, phase: 'Execução/cobrança' },
    { name: 'EMBARGOS À EXECUÇÃO', points: 150, phase: 'Execução/cobrança' },
    { name: 'EMBARGOS DE DECLARAÇÃO', points: 70, phase: 'Judicial' },
    { name: 'EMBARGOS INFRINGENTES', points: 100, phase: 'Recursal' },
    { name: 'EMENDA À INICIAL', points: 70, phase: 'Judicial' },
    { name: 'EMISSÃO DE PARECER', points: 10, phase: 'Negociação' },
    { name: 'EMITIR BOLETO', points: 10, phase: 'Administrativo' },
    { name: 'EMITIR CONTRATO DE HONORÁRIOS', points: 10, phase: 'Negociação' },
    { name: 'EMITIR GUIA DE CUSTAS - PARCELAMENTO', points: 20, phase: 'Judicial' },
    { name: 'EXPEDIÇÃO DE ALVARÁ', points: 30, phase: 'Execução/cobrança' },
    { name: 'EXPEDIR CERTIDÕES', points: 15, phase: 'Administrativo' },
    { name: 'FAZER ADMISSÃO DE COLABORADOR', points: 50, phase: 'Rh/financeiro' },
    { name: 'FAZER ALTERAÇÕES REQUERIDAS PELA FAZENDA', points: 15, phase: 'Judicial' },
    { name: 'FAZER DEMISSÃO DE COLABORADOR', points: 50, phase: 'Rh/financeiro' },
    { name: 'FAZER ENTREVISTA DE COLABORADOR', points: 100, phase: 'Rh/financeiro' },
    { name: 'FAZER BRIEFING', points: 40, phase: 'Marketing' },
    { name: 'FAZER RELATÓRIO DE COMISSÃO MENSAL DO PARCEIRO', points: 50, phase: 'Marketing' },
    { name: 'FECHAMENTO COM COBRANÇA INICIAIS', points: 200, phase: 'Negociação' },
    { name: 'FECHAMENTO COM HONORÁRIOS RECORRENTES', points: 200, phase: 'Negociação' },
    { name: 'FECHAMENTO SEM COBRANÇA INICIAIS', points: 120, phase: 'Negociação' },
    { name: 'GERENCIAR ANÚNCIOS DO ESCRITÓRIO SEMANAL', points: 200, phase: 'Marketing' },
    { name: 'IMPUGNAÇÃO À PENHORA', points: 100, phase: 'Execução/cobrança' },
    { name: 'IMPUGNAÇÃO A PERÍCIA JUDICIAL', points: 120, phase: 'Judicial' },
    { name: 'IMPUGNAÇÃO AO CÁLCULO', points: 100, phase: 'Execução/cobrança' },
    { name: 'INFORMAR CLIENTE DO ANDAMENTO DO PROCESSO', points: 10, phase: 'Judicial' },
    { name: 'INFORMAR O CLIENTE DA DECISÃO', points: 10, phase: 'Judicial' },
    { name: 'INTIMAÇÃO INSS PARA IMPLANTAR BENEFÍCIO', points: 20, phase: 'Execução/cobrança' },
    { name: 'INVESTIGAÇÃO PRIVADA', points: 200, phase: 'Administrativo' },
    { name: 'IR AO BANCO', points: 20, phase: 'Rh/financeiro' },
    { name: 'LEVANTAMENTO DE ALVARÁ', points: 20, phase: 'Execução/cobrança' },
    { name: 'LEVANTAMENTO DE RPV', points: 70, phase: 'Rh/financeiro' },
    { name: 'LIGAR PARA A PARTE CONTRÁRIA/ADVOGADO', points: 20, phase: 'Administrativo' },
    { name: 'LIMPEZA DO ESCRITÓRIO', points: 100, phase: 'Rh/financeiro' },
    { name: 'NEGOCIAR CONTRATO DE PARCERIA', points: 100, phase: 'Marketing' },
    { name: 'OBTER PROVA', points: 50, phase: 'Administrativo' },
    { name: 'OPORTUNIDADE GERADA', points: 50, phase: 'Negociação' },
    { name: 'ORGANIZAR AGENDAS', points: 100, phase: 'Rh/financeiro' },
    { name: 'ORGANIZAR CONTAS A PAGAR', points: 30, phase: 'Rh/financeiro' },
    { name: 'ORGANIZAR DOCUMENTOS', points: 10, phase: 'Todas' },
    { name: 'PAGAR CONTAS INTERNET BANKING', points: 10, phase: 'Rh/financeiro' },
    { name: 'PAGAR PARCEIROS', points: 50, phase: 'Rh/financeiro' },
    { name: 'PAGAR SALÁRIO', points: 15, phase: 'Rh/financeiro' },
    { name: 'PAGAR/REPASSAR VALOR PARA CLIENTE', points: 50, phase: 'Rh/financeiro' },
    { name: 'PARTICIPAR DE EVENTO', points: 50, phase: 'Marketing' },
    { name: 'PETIÇÃO INTERMEDIÁRIA', points: 30, phase: 'Judicial' },
    { name: 'PREPARAR SUSTENTAÇÃO ORAL', points: 100, phase: 'Recursal' },
    { name: 'PREPARAR TESTEMUNHAS', points: 50, phase: 'Judicial' },
    { name: 'PRODUÇÃO DE PROVAS - COLETA DE DOCUMENTOS E TESTEMUNHAS', points: 120, phase: 'Judicial' },
    { name: 'PROTESTO ANTI PRECLUSIVO', points: 30, phase: 'Judicial' },
    { name: 'PROTOCOLO REQUERIMENTO', points: 5, phase: 'Administrativo' },
    { name: 'PROTOCOLO/ENVIO CORREIOS', points: 30, phase: 'Rh/financeiro' },
    { name: 'RECLAMAÇÃO', points: 200, phase: 'Recursal' },
    { name: 'RECURSO DE APELAÇÃO/INOMINADO', points: 130, phase: 'Recursal' },
    { name: 'RECURSO ESPECIAL', points: 150, phase: 'Recursal' },
    { name: 'RECURSO ESPECIAL E EXTRAORDINÁRIO', points: 400, phase: 'Recursal' },
    { name: 'RECURSO EXTRAORDINÁRIO', points: 150, phase: 'Recursal' },
    { name: 'RELATÓRIO DE AUDIÊNCIA', points: 5, phase: 'Judicial' },
    { name: 'RELATÓRIO FINANCEIRO MENSAL', points: 50, phase: 'Rh/financeiro' },
    { name: 'RÉPLICA/IMPUGNAÇÃO À CONTESTAÇÃO', points: 110, phase: 'Judicial' },
    { name: 'RESPONDER DÚVIDAS DO CLIENTE', points: 25, phase: 'Negociação' },
    { name: 'REUNIÃO COM PARCEIRO', points: 50, phase: 'Marketing' },
    { name: 'REVOGAÇÃO DE MANDATO', points: 10, phase: 'Administrativo' },
    { name: 'SAQUE DOS HONORÁRIOS NO BANCO', points: 30, phase: 'Administrativo' },
    { name: 'SOLICITAR DESISTÊNCIA', points: 10, phase: 'Administrativo' },
    { name: 'SOLICITAR DOCUMENTOS', points: 10, phase: 'Todas' },
    { name: 'SOLICITAR INFORMAÇÕES DO CLIENTE', points: 10, phase: 'Todas' },
    { name: 'SOLICITAR REEMBOLSO PARA O CLIENTE', points: 50, phase: 'Rh/financeiro' },
    { name: 'SUSTENTAÇÃO ORAL TRT TRF TJ', points: 180, phase: 'Recursal' },
    { name: 'SUSTENTAÇÃO ORAL TST STJ STF', points: 200, phase: 'Recursal' },
    { name: 'TENTAR ACORDO EXTRAJUDICIAL', points: 100, phase: 'Administrativo' },
    { name: 'VIDEOCHAMADA OU LIGAÇÃO +30MIN', points: 75, phase: 'Negociação' },
    { name: 'VISITAR POSSÍVEIS CLIENTES', points: 50, phase: 'Marketing' }
  ];

  const actionTypes = [
    { name: 'ABERTURA DE INVENTÁRIO E PARTILHA', group: 'Serviços' },
    { name: 'AÇÃO ADMINISTRATIVA', group: 'Administrativo' },
    { name: 'AÇÃO AMBIENTAL', group: 'Cível' },
    { name: 'AÇÃO ANULATÓRIA', group: 'Cível' },
    { name: 'AÇÃO COLETIVA', group: 'Cível' },
    { name: 'AÇÃO CONTRA A UNIÃO FEDERAL', group: 'Administrativo' },
    { name: 'AÇÃO CRIMINAL', group: 'Criminal' },
    { name: 'AÇÃO DE APOSENTADORIA', group: 'Previdenciário' },
    { name: 'AÇÃO DE COBRANÇA', group: 'Cível' },
    { name: 'AÇÃO DE COBRANÇA DE COBERTURA SECURITÁRIA', group: 'Cível' },
    { name: 'AÇÃO DE CORREÇÃO DO FGTS', group: 'Previdenciário' },
    { name: 'AÇÃO DE DESAPOSENTAÇÃO', group: 'Administrativo' },
    { name: 'AÇÃO DE EXECUÇÃO', group: 'Cível' },
    { name: 'AÇÃO DE GUARDA', group: 'Família' },
    { name: 'AÇÃO DE INDENIZAÇÃO POR DANOS MATERIAIS', group: 'Cível' },
    { name: 'AÇÃO DE MEDICAMENTOS', group: 'Administrativo' },
    { name: 'AÇÃO DE POUPANÇA / EXPURGOS', group: 'Consumidor' },
    { name: 'AÇÃO DE REGULAMENTAÇÃO DE VISITA', group: 'Família' },
    { name: 'AÇÃO DE REVISÃO DO TETO', group: 'Previdenciário' },
    { name: 'AÇÃO DECLARATÓRIA DE INEXISTÊNCIA DE DÉBITO', group: 'Consumidor' },
    { name: 'AÇÃO INDENIZATÓRIA (DANO MORAL)', group: 'Cível' },
    { name: 'AÇÃO MERAMENTE DECLARATÓRIA', group: 'Trabalhista' },
    { name: 'AÇÃO MONITÓRIA', group: 'Cível' },
    { name: 'AÇÃO NO JUIZADO ESPECIAL CÍVEL', group: 'Cível' },
    { name: 'AÇÃO ORDINÁRIA', group: 'Cível' },
    { name: 'AÇÃO PENAL', group: 'Criminal' },
    { name: 'AÇÃO RESCISÓRIA', group: 'Cível' },
    { name: 'AÇÃO REVISIONAL DE CONTRATO', group: 'Consumidor' },
    { name: 'AÇÃO TRIBUTÁRIA', group: 'Tributário' },
    { name: 'ACIDENTE DE TRABALHO', group: 'Trabalhista' },
    { name: 'ACIDENTE DE TRÂNSITO', group: 'Cível' },
    { name: 'ACOMPANHAMENTO DE PROCESSO', group: 'Serviços' },
    { name: 'ACORDO DE NÃO PERSECUÇÃO PENAL', group: 'Criminal' },
    { name: 'ADIMPLEMENTO E EXTINÇÃO', group: 'Cível' },
    { name: 'AGRAVO DE INSTRUMENTO', group: 'Cível' },
    { name: 'AGRAVO EM RECURSO ESPECIAL', group: 'Cível' },
    { name: 'AGRAVO INTERNO', group: 'Cível' },
    { name: 'ALIENAÇÃO FIDUCIÁRIA', group: 'Cível' },
    { name: 'ALIMENTOS E REVISÃO', group: 'Família' },
    { name: 'ALVARÁ JUDICIAL', group: 'Cível' },
    { name: 'ANÁLISE PREVIDENCIÁRIA / PLANEJAMENTO', group: 'Previdenciário' },
    { name: 'ANTECIPAÇÃO DE TUTELA / LIMINAR', group: 'Cível' },
    { name: 'ANULAÇÃO DE DÉBITO FISCAL', group: 'Tributário' },
    { name: 'APELAÇÃO CÍVEL', group: 'Cível' },
    { name: 'APOSENTADORIA DA PESSOA COM DEFICIÊNCIA', group: 'Previdenciário' },
    { name: 'APOSENTADORIA ESPECIAL', group: 'Previdenciário' },
    { name: 'APOSENTADORIA POR IDADE / HÍBRIDA', group: 'Previdenciário' },
    { name: 'APOSENTADORIA POR INCAPACIDADE / INVALIDEZ', group: 'Previdenciário' },
    { name: 'APOSENTADORIA POR TEMPO DE CONTRIBUIÇÃO', group: 'Previdenciário' },
    { name: 'APOSENTADORIA RURAL', group: 'Previdenciário' },
    { name: 'ASSISTÊNCIA JUDICIÁRIA GRATUITA', group: 'Cível' },
    { name: 'AUXÍLIO ACIDENTE', group: 'Previdenciário' },
    { name: 'AUXÍLIO DOENÇA', group: 'Previdenciário' },
    { name: 'AUXÍLIO RECLUSÃO', group: 'Previdenciário' },
    { name: 'BANCÁRIOS / REVISIONAL', group: 'Consumidor' },
    { name: 'BENEFÍCIO DE PRESTAÇÃO CONTINUADA (BPC/LOAS)', group: 'Previdenciário' },
    { name: 'BUSCA E APREENSÃO', group: 'Cível' },
    { name: 'CUMPRIMENTO DE SENTENÇA', group: 'Cível' },
    { name: 'DESPEJO POR FALTA DE PAGAMENTO', group: 'Cível' },
    { name: 'DISSOLUÇÃO DE UNIÃO ESTÁVEL', group: 'Família' },
    { name: 'DIVÓRCIO CONSENSUAL / LITIGIOSO', group: 'Família' },
    { name: 'EMBARGOS À EXECUÇÃO', group: 'Cível' },
    { name: 'EMBARGOS DE DECLARAÇÃO', group: 'Cível' },
    { name: 'EMBARGOS DE TERCEIRO', group: 'Cível' },
    { name: 'EMPRÉSTIMO CONSIGNADO / FRAUDE', group: 'Consumidor' },
    { name: 'EXECUÇÃO DE ALIMENTOS', group: 'Família' },
    { name: 'EXECUÇÃO DE HONORÁRIOS', group: 'Cível' },
    { name: 'EXECUÇÃO DE TÍTULO EXTRAJUDICIAL', group: 'Cível' },
    { name: 'EXECUÇÃO FISCAL', group: 'Tributário' },
    { name: 'HABEAS CORPUS', group: 'Criminal' },
    { name: 'IMPUGNAÇÃO AO CUMPRIMENTO DE SENTENÇA', group: 'Cível' },
    { name: 'INDENIZAÇÃO POR DANO MORAL E MATERIAL', group: 'Cível' },
    { name: 'INVENTÁRIO E PARTILHA (JUDICIAL / EXTRAJUDICIAL)', group: 'Família' },
    { name: 'MANDADO DE SEGURANÇA', group: 'Cível' },
    { name: 'PENSÃO POR MORTE URBANA / RURAL', group: 'Previdenciário' },
    { name: 'PRECATÓRIO ESTADUAL', group: 'Precatório' },
    { name: 'PRECATÓRIO FEDERAL', group: 'Precatório' },
    { name: 'RECLAMATÓRIA TRABALHISTA', group: 'Trabalhista' },
    { name: 'RECONHECIMENTO DE RELAÇÃO DE EMPREGO', group: 'Trabalhista' },
    { name: 'RECURSO DE REVISTA', group: 'Trabalhista' },
    { name: 'RECURSO ESPECIAL (STJ)', group: 'Cível' },
    { name: 'RECURSO EXTRAORDINÁRIO (STF)', group: 'Cível' },
    { name: 'RECURSO INOMINADO (JEC)', group: 'Cível' },
    { name: 'REVISÃO DA VIDA TODA', group: 'Previdenciário' },
    { name: 'USUCAPIÃO EXTRAORDINÁRIA / URBANA', group: 'Cível' },
    { name: 'VERBAS RESCISÓRIAS', group: 'Trabalhista' }
  ];

  const stages = [
    { name: 'AÇÃO PROTOCOLADA/INICIADA', phase: 'Judicial', classification: 'Inicial' },
    { name: 'ACORDO HOMOLOGADO', phase: 'Judicial', classification: 'Acordo' },
    { name: 'AGENDADA REUNIÃO DE COMPOSIÇÃO DE ACORDO', phase: 'Consultoria', classification: 'Atendimento' },
    { name: 'AGENDADO ATENDIMENTO NO ÓRGÃO', phase: 'Administrativo', classification: 'Atendimento' },
    { name: 'AGENDAR CONSULTA', phase: 'Negociação', classification: 'Lead' },
    { name: 'AGUARDA AUDIÊNCIA', phase: 'Judicial', classification: 'Audiência' },
    { name: 'AGUARDA DECISÃO REFERENTE A PRECATÓRIO COMPLEMENTAR', phase: 'Judicial', classification: 'Execução' },
    { name: 'AGUARDA PAGAMENTO PRECATÓRIO', phase: 'Judicial', classification: 'Pagamento' },
    { name: 'AGUARDA PAGAMENTO RPV', phase: 'Judicial', classification: 'Pagamento' },
    { name: 'AGUARDA SENTENÇA', phase: 'Judicial', classification: 'Julgamento' },
    { name: 'AGUARDANDO CÓPIA DO PROCESSO ADMINISTRATIVO', phase: 'Administrativo', classification: 'Diligência' },
    { name: 'AGUARDANDO DECISÃO DO ÓRGÃO', phase: 'Administrativo', classification: 'Decisão' },
    { name: 'AGUARDANDO DECISÃO DO RECURSO', phase: 'Administrativo', classification: 'Recurso' },
    { name: 'AGUARDANDO DECISÃO DO TRIBUNAL', phase: 'Execução/cobrança', classification: 'Tribunal' },
    { name: 'AGUARDANDO DOCUMENTOS', phase: 'Negociação', classification: 'Documentação' },
    { name: 'AGUARDANDO JULGAMENTO', phase: 'Judicial', classification: 'Julgamento' },
    { name: 'AGUARDANDO JULGAMENTO DA EXECUÇÃO', phase: 'Execução/cobrança', classification: 'Julgamento' },
    { name: 'AGUARDANDO JULGAMENTO DO RECURSO', phase: 'Recursal', classification: 'Recurso' },
    { name: 'AGUARDANDO MANIFESTAÇÃO DA PARTE CONTRÁRIA', phase: 'Judicial', classification: 'Contraditório' },
    { name: 'AGUARDANDO PAGAMENTO DE CONDENAÇÃO', phase: 'Execução/cobrança', classification: 'Cobrança' },
    { name: 'AGUARDANDO PENHORA', phase: 'Execução/cobrança', classification: 'Penhora' },
    { name: 'AGUARDANDO SENTENÇA DE LIQUIDAÇÃO', phase: 'Execução/cobrança', classification: 'Liquidação' },
    { name: 'ANALISADO E NÃO DISTRIBUÍDO', phase: 'Arquivamento', classification: 'Descarte' },
    { name: 'ANÁLISE DE RESULTADOS', phase: 'Marketing', classification: 'Gestão' },
    { name: 'ANÁLISE DO CASO', phase: 'Negociação', classification: 'Triagem' },
    { name: 'APRESENTAÇÃO DE PROPOSTA', phase: 'Negociação', classification: 'Comercial' },
    { name: 'APRESENTADA RESPOSTA A RECURSO (CONTRARRAZÕES)', phase: 'Recursal', classification: 'Recurso' },
    { name: 'APRESENTADO RECURSO', phase: 'Execução/cobrança', classification: 'Recurso' },
    { name: 'ARQUIVADO POR DESINTERESSE CLIENTE', phase: 'Arquivamento', classification: 'Encerrado' },
    { name: 'ARQUIVADO POR DETERMINAÇÃO JUDICIAL', phase: 'Arquivamento', classification: 'Encerrado' },
    { name: 'ARQUIVADO/ENCERRADO', phase: 'Arquivamento', classification: 'Encerrado' },
    { name: 'ATENDENDO EXIGÊNCIAS', phase: 'Administrativo', classification: 'Exigência' },
    { name: 'CÁLCULOS EXECUÇÃO', phase: 'Judicial', classification: 'Cálculo' },
    { name: 'CITAÇÃO DO RÉU', phase: 'Judicial', classification: 'Citação' },
    { name: 'CITAÇÃO DO DEVEDOR PARA PAGAMENTO', phase: 'Execução/cobrança', classification: 'Citação' },
    { name: 'CONCILIAÇÃO / MEDIAÇÃO', phase: 'Judicial', classification: 'Acordo' },
    { name: 'CUMPRIMENTO DE SENTENÇA', phase: 'Judicial', classification: 'Execução' },
    { name: 'DESENVOLVENDO INICIAL DE AÇÃO JUDICIAL', phase: 'Judicial', classification: 'Redação' },
    { name: 'DESENVOLVENDO RECURSO AOS TRIBUNAIS SUPERIORES', phase: 'Recursal', classification: 'Redação' },
    { name: 'ELABORAÇÃO DE PARECER JURÍDICO', phase: 'Consultoria', classification: 'Parecer' },
    { name: 'EMBARGOS À EXECUÇÃO OPOSTOS', phase: 'Execução/cobrança', classification: 'Defesa' },
    { name: 'INSTRUÇÃO E JULGAMENTO', phase: 'Judicial', classification: 'Instrução' },
    { name: 'LIQUIDAÇÃO DE SENTENÇA', phase: 'Judicial', classification: 'Cálculo' },
    { name: 'MANIFESTAÇÃO QUANTO À CONTESTAÇÃO / RÉPLICA', phase: 'Judicial', classification: 'Manifestação' },
    { name: 'RECURSO ADMINISTRATIVO PROTOCOLADO', phase: 'Administrativo', classification: 'Recurso' },
    { name: 'RECURSO ESPECIAL E EXTRAORDINÁRIO', phase: 'Recursal', classification: 'Recurso' },
    { name: 'RECURSO PROTOCOLADO/INICIADO', phase: 'Recursal', classification: 'Recurso' },
    { name: 'RPV EMITIDO', phase: 'Execução/cobrança', classification: 'Pagamento' },
    { name: 'SENTENÇA PROFERIDA', phase: 'Judicial', classification: 'Decisão' },
    { name: 'SUSPENSO, AGUARDA JULG. REPERCUSSÃO GERAL', phase: 'Judicial', classification: 'Sobrestado' },
    { name: 'TRÂNSITO EM JULGADO / PROCESSO FINALIZADO', phase: 'Judicial', classification: 'Fim' }
  ];

  const origins = [
    { name: 'Indicação de Cliente' },
    { name: 'Indicação de Parceiro / Correspondente' },
    { name: 'Marketing Digital / Google Ads' },
    { name: 'Redes Sociais / Instagram' },
    { name: 'Atendimento Presencial / Balcão' },
    { name: 'Convênio / Sindicato / Associação' },
    { name: 'Site Institucional / WhatsApp' }
  ];

  const goals = [
    { group: 'Cível', monthlyClosings: 10 },
    { group: 'Previdenciário', monthlyClosings: 15 },
    { group: 'Trabalhista', monthlyClosings: 8 },
    { group: 'Tributário', monthlyClosings: 5 },
    { group: 'Família', monthlyClosings: 6 }
  ];

  const users = [
    { name: 'Ricardo De Luca Rossetto', role: 'Advogado Titular', pointsGoal: 1500 },
    { name: 'Equipe de Apoio Jurídico', role: 'Controladoria & Prazos', pointsGoal: 1000 }
  ];

  const inboxSections = [
    { value: 'Novas intimações' },
    { value: 'Publicações do DJEN' },
    { value: 'Andamentos DataJud' },
    { value: 'Tarefas urgentes' },
    { value: 'Prazos em dias úteis' }
  ];

  const notificationAssignments = [
    { event: 'Publicação capturada do DJEN', responsibles: 'Ricardo De Luca Rossetto, Equipe de Apoio Jurídico' },
    { event: 'Prazo fatal a vencer em 48h', responsibles: 'Ricardo De Luca Rossetto' },
    { event: 'Andamento capturado nos tribunais', responsibles: 'Equipe de Apoio Jurídico' }
  ];

  const integrations = [
    { name: 'DJEN / CNJ Diário Eletrônico', status: 'Ativo', method: 'API Oficial Pública' },
    { name: 'DataJud / CNJ Metadados', status: 'Ativo', method: 'API Oficial Pública' },
    { name: 'Google Gemini Flash IA', status: 'Ativo', method: 'REST API' },
    { name: 'Webcal / Google Agenda', status: 'Ativo', method: 'Sincronização iCal' },
    { name: 'Portais PJe / eproc (A1 + TOTP)', status: 'Preparado', method: 'Agente Local Seguro' }
  ];

  return {
    actionGroups,
    taskDefinitions,
    actionTypes,
    stages,
    origins,
    goals,
    users,
    inboxSections,
    notificationAssignments,
    integrations
  };
}));
